name: Build ImmortalWrt

on: 
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Free Disk Space (清理磁盘空间)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo -E apt-get clean

      - name: Initialization Environment (初始化环境)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install build-essential gettext asciidoc binutils bzip2 gawk git libncurses5-dev libz-dev patch python3 python3-pip rsync unzip zlib1g-dev libssl-dev wget subversion swig flex bison upx-ucl
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone Source Code (拉取源码)
        run: |
          git clone -b openwrt-23.05 https://github.com/immortalwrt/immortalwrt.git openwrt

      - name: Copy Custom Config (应用配置文件)
        run: |
          cp .config openwrt/.config

      - name: Update Feeds & Download Package (预下载编译依赖包)
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          # 核心修复：强制先编译宿主机打包工具 usign，防止 package index 打包报错
          make tools/usign/compile V=s
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Start Building Firmware (开始编译固件)
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload Artifacts (上传编译好的固件)
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-R619AC-Firmware
          path: openwrt/bin/targets/**/*.bin
